version: "3.7"
services:
  nginx:
    image: nginx:1.20.0
    container_name: fashion-shop-microservices-nginx
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - fashion-shop-microservices
    depends_on:
      - auth-service
  auth-service:
    build:
      context: ./
      dockerfile: ./auth-service/Dockerfile
    container_name: fashion-shop-microservices-auth-service
    command: bash -c "python auth-service/auth_service/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/var/www/auth-service
    ports:
      - 8000:8000
    networks:
      fashion-shop-microservices:
        aliases:
          - fashion-shop-microservices-network-auth-service
    depends_on:
      - auth-service-db
  auth-service-db:
    image: postgres:13.2
    container_name: fashion-shop-microservices-auth-service-db
    ports:
      - 5432:5432
    env_file:
      - ./auth-service/.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB}
    volumes:
      - auth-data:/var/lib/postgresql/data

volumes:
  auth-data:
    driver: local

networks:
  fashion-shop-microservices:
